---
title: "Deskriptive Statistik"
output: html_notebook
---


```{r}
library(tidyverse)
data <- c(1,5,3,20,15,25,3,8,6,9)
data <- sample(1000)
```

```{r}
#data <- as.data.frame(data)
ggplot() +
  geom_density(aes(data))

ggplot() +
  geom_boxplot(aes("",data))
```



# Arithmetisches Mittel

```{r}
xbar = sum(data) / length(data)
xbar

mean(data)
```

# Gestutztes Mittel

```{r}
mean_short <- function(v){
  v_sort <- sort(v)
  v_short <- v_sort[2:(length(v)-1)]
  sum(v_short) / length(v_short)
}

# cut off first and last element of the vector
mean_short(data)
```

# Median

```{r}
#data_sort[5]
my_median <- function(v){
  # getting number of elements
  n = count(as.data.frame(v))
  v_sort <- sort(v)
  # depending on even or odd numbers values is chosen differently
  if((n %% 2 == 0)){
    # getting mean of both middle numbers
    (v_sort[as.integer(n/2)] + v_sort[as.integer((n/2)+1)]) / 2
  } else{
    # getting values of middle number
    i = (n + 1)/2
    v_sort[as.integer(i)]
  }}

my_median(data)

# using the function from dplyr
median(data)
```

# Modus

```{r}
mode <- function(v) {
  # use table to find n of occurences of each element in vector
  table <- table(v)
  # find index with highest number
  max <- max(table)
  # select the value with max occurence
  unique(sort(v))[max]
}

mode(data)
```

# Empirische Varianz

```{r}
my_var <- function(v) {
  # first get the mean
  m <- mean(v)
  s <- 0
  for(i in 1:length(v)){
    # each value - the mean squared
    x <- (v[i]-m)**2
    s <- s + x
  }
  # divided by the number of values
  s <- s / length(v)
  return(s)
}

my_var(data)

# the r standard function is using the theoretische Varianz
var(data)
```

# empirische Standardabweichung

```{r}
my_var <- function(v) {
  # first get the mean
  m <- mean(v)
  s <- 0
  for(i in 1:length(v)){
    # each value - the mean squared
    x <- (v[i]-m)**2
    s <- s + x
  }
  # divided by the number of values; the root of this value
  s <- sqrt(s / length(v))
  return(s)
}

my_var(data)

# the r standard function is using the theoretische Standardabweichung
sd(data)
```

# Variationskoeffizient

```{r}
cv <- function(v){
  return (sd(v) / mean(v))
}
cv(data)
```

# Quartilsdifferenz

```{r}
my_iqr <- function(v){
  # getting number of elements
  n = length(v)
  v_sort <- sort(v)
  # depending on even or odd numbers values is chosen differently
  if((n %% 2 == 0)){
    # first quartile
    q1 <- v_sort[n*0.25]
    # third quartile
    q3 <- v_sort[n*0.75]
    print(q3)
    return(q3-q1)
  } else{
    # first quartile
    v1_q1 <- v_sort[n*0.25] 
    v2_q1 <- v_sort[n*0.25+1]
    q1 <- (v1_q1+v2_q1)/2
    # third quartile
    v1_q3 <- v_sort[n*0.75] 
    v2_q3 <- v_sort[n*0.75+1]
    q3 <- (v1_q3+v2_q3)/2
    
    return(q3-q1)
  }
}

my_iqr(data)

IQR(data)

sort(data)
```

# Medianabweichung

```{r}
my_mad <- function(v) {
  # first get the mean
  m <- median(v)
  s <- c()
  for(i in 1:length(v)){
    # each value - the mean squared
    x <- abs(v[i]-m)
    # adding each value to the new vector
    s <- c(s, x)
  }
  # median of the new vector
  s <- median(s)
  return(s)
}

my_mad(data)

# using the r function
mad(data) / 1.4826
```

# Schiefemasse (Skewness)

```{r}
skewness <- function(v) {
  # first get the mean
  mean <- mean(v)
  m <- 0
  for(i in 1:length(v)){
    # each value - the mean squared
    x <- (v[i]-mean)**3
    m <- m + x
  }
  # 
  m <- m/length(v)
  gm <- m/sd(v)**3
  return(gm)
}

skewness(data)

#using the r function
moments::skewness(data)
```

# Wölbungsmasse (Kurtosis)

```{r}
kurtosis <- function(v) {
  # first get the mean
  mean <- mean(v)
  m <- 0
  for(i in 1:length(v)){
    # each value - the mean squared
    x <- (v[i]-mean)**4
    m <- m + x
  }
  # 
  m <- m/length(v)
  y <- m/sd(v)**4
  return(y)
}

kurtosis(data)

#using the r function
moments::kurtosis(data)
```



